/* Generated By:JavaCC: Do not edit this line. ParserPolinomiosConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPolinomiosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 1;
  /** RegularExpression Id. */
  int IGUAL = 2;
  /** RegularExpression Id. */
  int NUMERO = 3;
  /** RegularExpression Id. */
  int PYC = 4;
  /** RegularExpression Id. */
  int MAS = 5;
  /** RegularExpression Id. */
  int MENOS = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"X\"",
    "\"=\"",
    "<NUMERO>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
